### ISSUE TITLE
Adding new row CSS

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-panels#152]
Hi.

Im trying to create a funktion on the row layout panel that adds a gradient overlay to the row.

CSS wise i use a `:before` selector that adds a gradient between the row background image and the row content.
I have successfully added the fields to the admin no i need to generate the css and thats where i hit a snag.

I want to generate something resembling the following:

```css
"The row instance":before {
  background-image: linear-gradient(to left, "ROW BACKGROUND COLOR" 0%, "ROW BACKGROUND COLOR" 100%);
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
}
```

I am adding these changes through an addon plugin. How would i go about adding this?

[Here](https://github.com/Jursdotme/secondthought-pagebuilder-bundle) is the plugin is its current addon plugin release.
